name: MUtils-World-Creator
load: STARTUP
version: 100
main: de.miraculixx.mutils.MWorlds
api-version: 1.16
authors: [ Miraculixx ]
description: MUtils World Creator - Create and manage your own worlds with full control over world generation
website: https://mutils.de/
libraries:
  - "org.jetbrains.kotlin:kotlin-stdlib:1.9.10"
  - "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4"
  - "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8:1.6.4"
  - "org.jetbrains.kotlinx:kotlinx-serialization-json:1.5.1"
  - "io.ktor:ktor-client-cio-jvm:2.1.3"
  - "io.ktor:ktor-client-core-jvm:2.1.3"
  - "org.yaml:snakeyaml:1.33"
  - "dev.jorel:commandapi-bukkit-shade:9.2.0"
  - "dev.jorel:commandapi-bukkit-kotlin:9.2.0"

