#--------------->> MUtils Settings <<-----------------#
#             Global and general Settings             #
#   Nearly everything can be changed ingame without   #
#           any fear to destroy the system!           #
#------------>> Colors & Formatting <<----------------#
# §1-9 / a-o ('&' also works)                         #
# \n -> Next Line (NOT WORK ON ITEMS OR LISTS)        #
# Commands without Color Code automatically use §7    #
#                                                     #
#-----------------------------------------------------#


# Prefix (Main Menu/Settings/Prefix)
# -> Text - Supports Formatting. Last Color Codes define default Message Color
Prefix: "§8§l[§9GHG-Network§8§l]§7"

# Language (Main Menu/Settings/Language)
# -> Text-Key - MUtils use EN_EN.yml if EN_EN is set bellow.
# -> NOTE - File MUST be present in MUtils/language/...
Language: DE_DE

# Global GUI Style
# -> You can choose any Item, but Glass Panes works the best
# Default: GRAY_STAINED_GLASS_PANE - BLACK_STAINED_GLASS_PANE
Placeholder 1: GRAY_STAINED_GLASS_PANE
Placeholder 2: BLACK_STAINED_GLASS_PANE

# Reset (/reset)
# -> false & true - Delete every world (Can not be undone!)
Reset: false

# Seed (Main Menu/World Manger/Seed)
# -> Number & 'none' - Every new world will be generated with this seed
Seed: none

#--------------->> Server Settings <<-----------------#
#              Settings around the server             #
#-----------------------------------------------------#

# Server Icon in Server List
# -> Path from server folder (e.g. plugins/MUtils/customIcon.png)
Server Icon: icon.png

# Server MOTD in Server List
# -> Text Value - Color Codes and formatting (\n for line break)
MOTD: "          §eMinecraft Server\n§7≪ §2Powered by MUtils §7≫"

# Server Slots in Server List
# -> Number
Slots: 20

# !!! BETA !!!
# This Feature is in a Test-Phase. It may corrupt your settings.
#
# Sync Settings
# 'Sync' will use the data from cloud if present (on server start)
# 'Sync Update' will update the cloud data from local (on server stop)
# -> BOOLEAN - true / false (yes / no)
Sync Load:
  Modules: false
Sync Update:
  Modules: false


#--------------->> Server Settings <<-----------------#
#              Settings around the server             #
#-----------------------------------------------------#

# Server Icon in Server List
# -> Path from server folder (e.g. plugins/MUtils/customIcon.png)
Server Icon: icon.png

# Server MOTD in Server List
# -> Text Value - Color Codes and formatting (\n for line break)
MOTD: "          §eMinecraft Server\n§7≪ §2Powered by MUtils §7≫"

# Server Slots in Server List
# -> Number
Slots: 20

# !!! BETA !!!
# This Feature is in a Test-Phase. It may corrupt your settings.
#
# Sync Settings
# 'Sync' will use the data from cloud if present (on server start)
# 'Sync Update' will update the cloud data from local (on server stop)
# -> BOOLEAN - true / false (yes / no)
Sync Load:
  Modules: false
Sync Update:
  Modules: false


