name: MUtils-Challenge-Addon
load: STARTUP
version: 103
main: de.miraculixx.challenge.addon.MAddon
api-version: 1.16
authors: [ Miraculixx ]
description: MUtils Challenges - Play various Challenges that can modify the game slightly to completely against or in coop with your friends!
website: https://mutils.de/
softdepend: [ MUtils-Challenge ]
libraries:
  - "org.jetbrains.kotlin:kotlin-stdlib:1.8.10"
  - "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.0-Beta"
  - "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8:1.7.0-Beta"
  - "org.jetbrains.kotlinx:kotlinx-serialization-json:1.4.1"
