name: MUtils-Challenge
load: STARTUP
version: 111
main: de.miraculixx.mchallenge.MChallenge
api-version: 1.16
authors: [ Miraculixx, "NoRisk" ]
description: MUtils Challenges - Play various Challenges that can modify the game slightly to completely against or in coop with your friends!
website: https://mutils.net/
softdepend: [ MUtils-Timer, MUtils-Web ]
libraries:
  - "org.jetbrains.kotlin:kotlin-stdlib:1.8.20"
  - "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.0-Beta"
  - "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8:1.7.0-Beta"
  - "org.jetbrains.kotlinx:kotlinx-serialization-json:1.5.0"
  - "io.ktor:ktor-client-core:2.1.3"
  - "io.ktor:ktor-client-cio:2.1.3"
  - "net.kyori:adventure-api:4.11.0"
  - "net.kyori:adventure-text-minimessage:4.11.0"
  - "net.kyori:adventure-text-serializer-plain:4.11.0"
  - "org.yaml:snakeyaml:1.33"

commands:
  mobhunt:
    permission: mutils.command.mobhunt
    description: Modify the Mob-Hunt challenge
  itemhunt:
    permission: mutils.command.itemhunt
    description: Modify the Item-Hunt challenge