name: Sync Modrinth

on:
  push:
    branches:
      - master
    paths:
      - 'README.md'

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Sync README
        run: ./gradlew modrinthSyncBody -modrinthToken=${{ env.MODRINTH_TOKEN }}
