name: Sync Modrinth

on:
  push:
    branches:
      - master
    paths:
      - 'README.md'

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Sync README
        run: ./gradlew modrinthSyncBody -PmodrinthToken=${{ env.MODRINTH_TOKEN }}
